In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('account_activity.csv')
df.head()

   CustomerID  AccountBalance   LastLogin
0        1001     9507.272060  2022-01-01
1        1002     7408.704536  2022-01-02
2        1003     1715.321989  2022-01-03
3        1004     3101.509134  2022-01-04
4        1005     5405.766914  2022-01-05

In [22]:
account_activity = pd.read_csv('account_activity.csv')
amount_data = pd.read_csv('amount_data.csv')
anomaly_scores = pd.read_csv('anomaly_scores.csv')
customer_data = pd.read_csv('customer_data.csv')
fraud_indicators = pd.read_csv('fraud_indicators.csv')
merchant_data = pd.read_csv('merchant_data.csv')
suspicious_activity = pd.read_csv('suspicious_activity.csv')
transaction_category_labels = pd.read_csv('transaction_category_labels.csv')
transaction_metadata = pd.read_csv('transaction_metadata.csv')
transaction_records = pd.read_csv('transaction_records.csv')

In [23]:
data = [account_activity, amount_data, anomaly_scores, customer_data, fraud_indicators, merchant_data, suspicious_activity, transaction_category_labels, transaction_metadata, transaction_records]

In [25]:
for df in data:
    print(df.head())

   CustomerID  AccountBalance   LastLogin
0        1001     9507.272060  2022-01-01
1        1002     7408.704536  2022-01-02
2        1003     1715.321989  2022-01-03
3        1004     3101.509134  2022-01-04
4        1005     5405.766914  2022-01-05
   TransactionID  TransactionAmount
0              1          79.413607
1              2          12.053087
2              3          33.310357
3              4          46.121117
4              5          54.051618
   TransactionID  AnomalyScore
0              1      0.686699
1              2      0.081749
2              3      0.023857
3              4      0.876994
4              5      0.034059
   CustomerID           Name  Age       Address
0        1001  Customer 1001   54  Address 1001
1        1002  Customer 1002   35  Address 1002
2        1003  Customer 1003   40  Address 1003
3        1004  Customer 1004   30  Address 1004
4        1005  Customer 1005   46  Address 1005
   TransactionID  FraudIndicator
0              1               0
1              2               0
2              3               0
3              4               0
4              5               0
   MerchantID   MerchantName       Location
0        2001  Merchant 2001  Location 2001
1        2002  Merchant 2002  Location 2002
2        2003  Merchant 2003  Location 2003
3        2004  Merchant 2004  Location 2004
4        2005  Merchant 2005  Location 2005
   CustomerID  SuspiciousFlag
0        1001               0
1        1002               0
2        1003               0
3        1004               0
4        1005               0
   TransactionID Category
0              1    Other
1              2   Online
2              3   Travel
3              4   Travel
4              5    Other
   TransactionID            Timestamp  MerchantID
0              1  2022-01-01 00:00:00        2701
1              2  2022-01-01 01:00:00        2070
2              3  2022-01-01 02:00:00        2238
3              4  2022-01-01 03:00:00        2879
4              5  2022-01-01 04:00:00        2966
   TransactionID     Amount  CustomerID
0              1  55.530334        1952
1              2  12.881180        1027
2              3  50.176322        1955
3              4  41.634001        1796
4              5  78.122853        1946

In [26]:
customer_data = pd.merge(customer_data, account_activity, on='CustomerID')
customer_data = pd.merge(customer_data, suspicious_activity, on='CustomerID')
customer_data

,CustomerID,Name,Age,Address,AccountBalance,LastLogin,SuspiciousFlag
0,1001,Customer 1001,54,Address 1001,9507.272060,2022-01-01,0
1,1002,Customer 1002,35,Address 1002,7408.704536,2022-01-02,0
2,1003,Customer 1003,40,Address 1003,1715.321989,2022-01-03,0
3,1004,Customer 1004,30,Address 1004,3101.509134,2022-01-04,0
4,1005,Customer 1005,46,Address 1005,5405.766914,2022-01-05,0
...,...,...,...,...,...,...,...
995,1996,Customer 1996,33,Address 1996,8523.485163,2024-09-22,0
996,1997,Customer 1997,58,Address 1997,9255.451757,2024-09-23,0
997,1998,Customer 1998,25,Address 1998,9148.652759,2024-09-24,0
998,1999,Customer 1999,57,Address 1999,7376.854107,2024-09-25,0
999,2000,Customer 2000,42,Address 2000,4853.024380,2024-09-26,0

In [28]:
transaction_data1 = pd.merge(fraud_indicators, transaction_category_labels, on='TransactionID')
transaction_data2 = pd.merge(amount_data, anomaly_scores, on='TransactionID')
transaction_data3 = pd.merge(transaction_metadata,transaction_records, on='TransactionID')
transaction_data = pd.merge(transaction_data1, transaction_data2,on="TransactionID")
transaction_data = pd.merge(transaction_data, transaction_data3,on="TransactionID")

In [29]:
transaction_data

,TransactionID,FraudIndicator,Category,TransactionAmount,AnomalyScore,Timestamp,MerchantID,Amount,CustomerID
0,1,0,Other,79.413607,0.686699,2022-01-01 00:00:00,2701,55.530334,1952
1,2,0,Online,12.053087,0.081749,2022-01-01 01:00:00,2070,12.881180,1027
2,3,0,Travel,33.310357,0.023857,2022-01-01 02:00:00,2238,50.176322,1955
3,4,0,Travel,46.121117,0.876994,2022-01-01 03:00:00,2879,41.634001,1796
4,5,0,Other,54.051618,0.034059,2022-01-01 04:00:00,2966,78.122853,1946
...,...,...,...,...,...,...,...,...,...
995,996,0,Food,89.457059,0.266778,2022-02-11 11:00:00,2150,19.876750,1411
996,997,0,Retail,47.958030,0.512483,2022-02-11 12:00:00,2888,96.299792,1566
997,998,0,Food,64.210046,0.367740,2022-02-11 13:00:00,2037,75.164459,1654
998,999,0,Travel,64.684167,0.960364,2022-02-11 14:00:00,2629,93.633040,1928
999,1000,0,Other,97.440127,0.311224,2022-02-11 15:00:00,2235,89.915625,1503